GMR.DefineSetting('Disable', 'Mount')
GMR.DefineSetting('Disable', 'FlyingMount')
GMR.DefineSetting('Disable', 'AvoidWater')
GMR.DefineSetting('Enable', 'FightOnTravels')
GMR.DefineSetting('Disable', 'Grinding')
GMR.DefineSetting('Disable', 'Sell')
GMR.DefineSetting('Disable', 'Repair')
GMR.DefineSetting('Disable', 'FoodDrink')
GMR.DefineSetting('Disable', 'MountVendoring')
GMR.DefineSetting('Disable', 'Hearthstone')
SetCVar('nameplateShowFriendlyNPCs', 1)
-- SetCVar('cameraSmoothStyle', 2)
SetCVar('SoftTargetInteract', 3)
SetCVar('SoftTargetIconInteract', 1)
SetCVar('SoftTargetIconGameObject', 1)
SetCVar('SoftTargetIconInteract', 1)
SetCVar('SoftTargetLowPriorityIcons', 1)
SetCVar('TargetEnemyAttacker', 1)
SetCVar('SoftTargetInteractRange', 1000)
-- /dump GetCVar('SoftTargetInteractRange')
-- /dump SetCVar('SoftTargetInteractRange', 50)
SetCVar('SoftTargetTooltipDurationMs', 99999999)
SetCVar('SoftTargetTooltipEnemy', 1)
SetCVar('SoftTargetTooltipFriend', 1)
SetCVar('SoftTargetTooltipInteract', 1)
SetCVar('SoftTargetTooltipLocked', 1)
-- /dump GetCVar('SoftTargetFriend')
-- SetCVar('SoftTargetFriend', 1)

C_Timer.After(0, efficientlyLevelToMaximumLevel)
